
var exMarker=[];var sight_list="";var objTemp;var t=0;var md_height=0;var param='';var sightseeing_search={getSearchCondition:function(){var data=new Object();param='';try{param=$('form[name=s_search]').serialize();}catch(error){param=null;}
return param;},htmlEntityDecode:function(str){var _tempElementId='json_area';var _returnString=null;if($("body")){$("body").append("<textarea id=\""+_tempElementId+"\" style=\"width:0;height:0;display:none;\"></textarea>");var oObj=$("#"+_tempElementId);oObj.html(str);_returnString=oObj.val();oObj.remove();oObj=null;_returnString=_returnString.split("&#039;").join("'");_returnString=_returnString.split("&#39;").join("'");}else{_returnString=false;}
return _returnString;},waitGetMarker:function(address,category){geocoder.geocode({'address':address},function(results,status){if(status==google.maps.GeocoderStatus.OK){var positionObj=results[0].geometry.location;var iconCate='/_assets/images/common/tours/sightseeing/i_marker_0'+obj.marker[i].category+'.png';var MarkerObj=new google.maps.Marker({position:positionObj,map:map,icon:iconCate});google.maps.event.addListener(MarkerObj,"click",function(event){var infoBox=new InfoBox({latlng:MarkerObj.getPosition(),map:map});});google.maps.event.trigger(MarkerObj,"click");exMarker.push(MarkerObj);}});},createMapLeftList:function(markerData){var myHtml="";try{var mySpan=$("<span/>");var myLi=$("<li/>");var myA=$("<a/>");var myTable=$("<table/>");var myTr=$("<tr/>");var myTd=$("<td/>");var myImg=$("<img/>");var myDiv=$("<div/>");var myDiv2=$("<div/>");myDiv2.attr("class","img_box");myA.attr("href","#map_canvas");myA.attr("pos_x",markerData.pos_x);myA.attr("pos_y",markerData.pos_y);myA.attr("pos_address",markerData.address);myA.attr("sightseeing_id",markerData.sightseeingid);myA.attr("category",markerData.category);myA.attr("sightseeing_title",markerData.title);myA.attr("onClick","sightseeing_search.mapLeftListClick(this);");if(markerData.image==''){myImg.attr("src","/_assets/images/common/tours/sightseeing/no_img.png");}else{myImg.attr("src","/cms_image/sightseeing/"+markerData.image);}
myImg.attr("alt","");if(myImg.attr("height")>myImg.attr("width")){var y=(55/myImg.attr("width"))*myImg.attr("height");myImg.css({width:'55px',height:y+'px'});}else{var w=(55/myImg.attr("height"))*myImg.attr("width");var ml=((w-55)/2)*-1;myImg.css({height:'55px',width:w+'px',marginLeft:ml+'px'});};myDiv2.append(myImg);myTd.append(myDiv2);myTr.append(myTd);myTable.append(myTr);myTable.attr("class","img");myDiv.attr("class","img");myDiv.html('<span>'+markerData.pref_str+'</span><br />'+markerData.title);myA.append(myTable);myA.append(myDiv);myLi.append(myA);mySpan.append(myLi);myHtml=mySpan.html();}catch(error){}
return myHtml;},mapLeftListClick:function(obj){try{var infoBox=new InfoBox({latlng:new google.maps.LatLng($(obj).attr("pos_x"),$(obj).attr("pos_y")),map:map,sightseeing_title:$(obj).attr("sightseeing_title"),sightseeing_id:$(obj).attr("sightseeing_id"),position_x:$(obj).attr("pos_x"),position_y:$(obj).attr("pos_y")});}catch(error){}},search:function(){try{var param=sightseeing_search.getSearchCondition();$.ajax({url:"./sightseeing_get_marker.html",dataType:"html",type:'POST',data:param,timeout:3000,success:function(html){try{var sight_list="";var jsondata=html;jsondata=sightseeing_search.htmlEntityDecode(jsondata);var obj=eval('('+jsondata+')');for(var i=0;i<obj.marker.length;i++){objTemp=obj.marker[i];if(obj.marker[i].pos_x!=null&&obj.marker[i].pos_y!=null){var positionObj=new google.maps.LatLng(obj.marker[i].pos_x,obj.marker[i].pos_y);var iconCate='/_assets/images/common/tours/sightseeing/i_marker_0'+obj.marker[i].category+'.png';var MarkerObj=new google.maps.Marker({position:positionObj,position_x:obj.marker[i].pos_x,position_y:obj.marker[i].pos_y,map:map,icon:iconCate,sightseeing_title:obj.marker[i].title,sightseeing_id:obj.marker[i].sightseeingid});google.maps.event.addListener(MarkerObj,"click",function(event){try{var positionObj=new google.maps.LatLng($(this).attr("position_x"),$(this).attr("position_y"));var infoBox=new InfoBox({latlng:positionObj,map:map,sightseeing_title:$(this).attr("sightseeing_title"),sightseeing_id:$(this).attr("sightseeing_id"),position_x:$(this).attr("position_x"),position_y:$(this).attr("position_y")});}catch(error){}});exMarker.push(MarkerObj);}else if(obj.marker[i].address!=null){var address=obj.marker[i].address;var iconCate='/_assets/images/common/tours/sightseeing/i_marker_0'+obj.marker[i].category+'.png';if(geocoder===null){geocoder=new google.maps.Geocoder();}
geocoder.geocode({'address':address},function(results,status){if(status==google.maps.GeocoderStatus.OK){var positionObj=results[0].geometry.location;var MarkerObj=new google.maps.Marker({position:positionObj,map:map,icon:iconCate});google.maps.event.addListener(MarkerObj,"click",function(event){var infoBox=new InfoBox({latlng:MarkerObj.getPosition(),map:map});});exMarker.push(MarkerObj);}
if(status==google.maps.GeocoderStatus.ERROR){setTimeout(function(){alert('住所からのマップマーカー取得に失敗しました。');},1000);}
if(status==google.maps.GeocoderStatus.OVER_QUERY_LIMIT){setTimeout(function(){sightseeing_search.waitGetMarker(address,objTemp.category);},1000);}
if(status==google.maps.GeocoderStatus.ZERO_RESULTS){}});}
sight_list+=sightseeing_search.createMapLeftList(obj.marker[i]);}
$('#marker_data .inner ul').html(sight_list);md_height=($('#marker_data .inner ul').innerHeight());if(md_height>428){$('#scrl_d a').addClass('a_swap');};$('.layer').fadeOut('slow');$('#first_view_layer').fadeOut('slow');}catch(error){}},error:function(XMLHttpRequest,textStatus,errorThrown){try{if(textStatus!=""){sightseeing_search.search();}}catch(error){}}});}catch(error){};}};$(window).ready(function(){var mp=map_area_btn();$('#s_search input').click(function(){if(param==''&&$('.map_area').css('display')=='block'){$('.map_area').slideUp('slow',function(){$('.map_area').css({top:'-9999px',position:'absolute',display:'block'});});};$
('#marker_data .inner ul').css('top',0);t=0;});$('.open_gmap').click(function(){var flg=$('.map_area').css('top');if(flg=='-9999px'&&param!=''){$(this).addClass('active');$('.map_area').css({top:'0px',position:'relative',display:'none'}).slideDown('slow');}else if(flg=='0px'&&param!=''){$(this).removeClass('active');$('.map_area').slideUp('slow',function(){$('.map_area').css({top:'-9999px',position:'absolute',display:'block'});});};});});function map_area_btn(){$('#marker_data .inner ul').css('top',t);$('#scrl_d a').click(function(){md_height=($('#marker_data .inner ul').innerHeight());if(md_height>428&&md_height>(t*-1)&&(md_height+t)>428){$('#scrl_d a').addClass('a_swap');t=t-428;$('#marker_data .inner ul').animate({top:t+'px'},{easing:"swing"});if(md_height>428&&t<=-428){$('#scrl_u a').addClass('a_swap');}}else{$('#scrl_d a').removeClass('a_swap');};if((md_height+t)<=428){$('#scrl_d a').removeClass('a_swap');}
return false;});$('#scrl_u a').click(function(){if(md_height>428&&t<=-428){$('#scrl_u a').addClass('a_swap');t=t+428;$('#marker_data .inner ul').animate({top:t+'px'},{easing:"swing"});if(md_height>428&&md_height>(t*-1)&&(md_height+t)>428){$('#scrl_d a').addClass('a_swap');}}else{$('#scrl_u a').removeClass('a_swap');};if(t>-428){$('#scrl_u a').removeClass('a_swap');}
return false;});}