
var map;var geocoder=new google.maps.Geocoder();var mapDetail;var selectCategory=[];var markersArray=[];function categoryView(category){try{if(category!="init"){var c_check=false;var checks=[];$("[name='cat[]']:checked").each(function(){checks.push(this.value);});for(i=0;i<checks.length;i++){if(category==checks[i]){c_check=true;break;}}
if(c_check==true){$("#category_box_"+category).css("display","");}else{$("#category_box_"+category).css("display","none");}}
deleteOverlays();var jsonData=sightseeing_search.search();}catch(e){alert("message: "+e);}}
function setCenter(pos_x,pos_y,address){if(pos_x!=null&&pos_y!=null){locate=new google.maps.LatLng(pos_x,pos_y);map.setCenter(locate);}else{geocoder.geocode({'address':address},function(results,status){if(status==google.maps.GeocoderStatus.OK){locate=results[0].geometry.location;map.setCenter(locate);}});}}
function ViewMapDetail(id){var pos_x=document.getElementById("pos_x["+id+"]").value;var pos_y=document.getElementById("pos_y["+id+"]").value;var position;if(pos_x==""&&pos_y==""){position=getPositionForAddress(id);var myOptions={zoom:13,center:position,mapTypeId:google.maps.MapTypeId.ROADMAP,disableDefaultUI:false};}else{position=new google.maps.LatLng(pos_x,pos_y);var myOptions={zoom:13,center:position,mapTypeId:google.maps.MapTypeId.ROADMAP,disableDefaultUI:true,zoomControl:true};}
mapDetail=new google.maps.Map(document.getElementById("map_canvas_mini"),myOptions);var Marker=new google.maps.Marker({position:position,map:mapDetail});}
function getPositionForAddress(id){try{var sad=document.getElementById("s_address["+id+"]").value;geocoder.geocode({'address':sad},function(results,status){if(status==google.maps.GeocoderStatus.OK){position=results[0].geometry.location;mapDetail.setCenter(results[0].geometry.location);Marker=new google.maps.Marker({position:position,map:mapDetail});Marker.setPosition(results[0].geometry.location);return position;}else{position=new google.maps.LatLng(0,0);alert('住所から場所を特定できませんでした。');return position;}});}catch(error){alert("messageB "+error);}}
function initialize(mode,centerName,lat,lng){try{var centerPosition=new google.maps.LatLng(lat,lng);var myOptions={zoom:13,center:centerPosition,mapTypeId:google.maps.MapTypeId.ROADMAP,disableDefaultUI:true,zoomControl:true,scrollwheel:false};map=new google.maps.Map(document.getElementById("map_canvas"),myOptions);if(mode=="init"){var CenterName=$('.hide_center_no').html();var iconCate='/_assets/images/common/logo/map/c_marker_0'+CenterName+'.png';var centerMarker=new google.maps.Marker({position:centerPosition,map:map,title:centerName,icon:iconCate});}
if(mode=="init"){var elem=document.getElementsByName("cat[]");for(index=0;index<elem.length;index++){elem[index].checked=true;}
categoryView("init");}}catch(error){alert("errorA:"+error);}}
function deleteOverlays(){if(exMarker){for(i in exMarker){exMarker[i].setMap(null);}
exMarker.length=0;}}
function viewLargeMap(){var item=$('#map_canvas').toggle();}