
var mapObj=new Array();var mapData=new Array();function printOut(){$(".print_button").css("display","none");window.print();}
$(window).load(function(){$('.print--break--before:last').removeClass('.print--break--before');});function initializeFacilitiesPrint(index){try{var latlng=new google.maps.LatLng(mapData[index].map_pos_x,mapData[index].map_pos_y);var myOptions={zoom:12,center:latlng,mapTypeId:google.maps.MapTypeId.ROADMAP};mapObj[index]=new google.maps.Map(document.getElementById('map_'+mapData[index].map_id),myOptions);var iconCate='/_assets/images/common/tours/sightseeing/i_marker_'+mapData[index].map_icon+'.png';var Marker=new google.maps.Marker({position:latlng,map:mapObj[index],icon:iconCate});var latlngCenter=new google.maps.LatLng(mapData[index].map_center_pos_x,mapData[index].map_center_pos_y);var iconCenter='/_assets/images/common/logo/map/c_marker_0'+mapData[index].map_center_icon+'.png';var MarkerCenter=new google.maps.Marker({position:latlngCenter,map:mapObj[index],icon:iconCenter});}catch(error){}}
function reZoom(index){try{mapObj[index].setZoom(13);}catch(error){}}
function notPrintSelect(id){var title=$("#title_"+id).val();if(window.confirm("「"+title+"」の印刷解除を行ないます。よろしいですか？")){facilities_search.getCategoryId(id);$("#c_facility_"+id).remove();$('.inst:last').addClass('last-inst');if($('.inst:last').length==0){window.close();};}}
var name="#sidebar";var menuYloc=null;var selectCategory=[];var mycenter=0;$(document).ready(function(){try{menuYloc=parseInt($(name).css("top").substring(0,$(name).css("top").indexOf("px")));$(window).scroll(function(){offset=menuYloc+$(document).scrollTop()+"px";$(name).animate({top:offset},{duration:500,queue:false});});}catch(error){}
$('.map a').each(function(){$(this).on('click',function(event){$('.btn_clear02').css('cursor','pointer');try{$('.map a').removeClass('on');$(this).addClass('on');if($(this).attr('id')=='c08'){$('.banner_campaign').css('display','block');}else{$('.banner_campaign').css('display','none');}
$('.all_pref_list').css('display','none');}catch(error){}});});$('.facility.pref_selector').each(function(){$(this).on('click',function(event){try{mycenter=$(this).attr('my_pref');facilities_search.updatePrefCheckbox($(this).attr('my_pref'),$(this).attr('my_checked'));var mychecked=$(this).attr('my_checked');if(mychecked==1){$(this).attr('my_checked',0);}else{$(this).attr('my_checked',1);}}catch(error){}});});$('.btn_pref_list').click(function(){if($('.all_pref_list').is(':hidden')){$('.btn_clear02').css('cursor','pointer');if(mycenter!=0){$('.center_pref_list_'+mycenter+' .pref_list').slideUp('slow',function(){$('.all_pref_list').css('display','block');$('.all_pref_list .pref_list').slideDown('slow');});}else{$('.all_pref_list').css('display','block');$('.all_pref_list .pref_list').slideDown('slow');};}else{if(mycenter!=0){$('.all_pref_list .pref_list').slideUp('slow',function(){$('.all_pref_list').css('display','none');$('.center_pref_list_'+mycenter+' .pref_list').slideDown('slow');});}else{$('.btn_clear02').css('cursor','default');$('.all_pref_list .pref_list').slideUp('slow',function(){$('.all_pref_list').css('display','none');});};}});$('.check-pref-item li input').each(function(){$(this).click(function(){if($(this).prop('checked')){$(this).addClass('active');}else{$(this).removeClass('active');}});});$('.btn_clear02').click(function(){$('.map a').removeClass('on');$('.btn_clear02').css('cursor','default');});categoryView("init");facilities_search.updateBrowsingPages("load");facilities_search.updatePrintTargetList();});$(window).unload(function(){facilities_search.updateBrowsingPages("unload");});function categoryView(category){try{if(category!="init"){var c_check=false;var checks=[];$("[name='cat[]']:checked").each(function(){checks.push(this.value);});for(i=0;i<checks.length;i++){if(category==checks[i]){c_check=true;break;}}
if(c_check==true){$(".cat_inst_"+category).css("display","");}else{$(".cat_inst_"+category).css("display","none");}}else{var elem=document.getElementsByName("cat[]");for(index=0;index<elem.length;index++){elem[index].checked=true;}}}catch(e){}};var facilities_search={isHasData:true,updateBrowsingPages:function(load){try{var myBrowsingKey="facilities_c_b";var myKeepKey="facilities_c";var myGetCookie=function GetCookie(key){var tmp=document.cookie+";";var index1=tmp.indexOf(key,0);if(index1!=-1){tmp=tmp.substring(index1,tmp.length);var index2=tmp.indexOf("=",0)+1;var index3=tmp.indexOf(";",index2);return(unescape(tmp.substring(index2,index3)));}
return("0");};var mySetCookie=function SetCookie(key,val){document.cookie=key+"="+escape(val)+";";};if(location.pathname.match(/^\/card\/facilities\//)){if(load=="load"){var myCount=myGetCookie(myBrowsingKey);myCount++;mySetCookie(myBrowsingKey,myCount);}else{var myCount=myGetCookie(myBrowsingKey);myCount--;if(myCount>=0){mySetCookie(myBrowsingKey,myCount);}
if(myCount<=0){mySetCookie(myKeepKey,"");}}}}catch(error){}},updateCenterPrefList:function(myCenter){try{$('.all_pref_list .pref_list').css('display','none');}catch(error){}},updatePrefCheckbox:function(myCenter,myChecked){try{var checked=false;if(myChecked==1){checked=false;}else{checked=true;}
$('span.center_pref_list_'+myCenter+' input[name="pref[]"]').attr("checked",checked);}catch(error){}},preSearch:function(tag){try{if($(tag).attr('mycenter')>0){$('span.all_pref_list input[name="pref[]"]').attr("checked",false);mycenter=$(tag).attr('mycenter');}else{mycenter=0;}
$('#locationid').attr('value',$(tag).attr('mycenter'));facilities_search.search();}catch(error){}},clearPrefCheckboxAll:function(is_clear_pref_list){try{$('.btn_clear02').css('cursor','default');$('.map a').removeClass('on');$('.nav_cate_h4_facility').slideUp('normal',function(){$('#facilities_result_area ul').empty();if(typeof is_clear_pref_list!="undefined"&&is_clear_pref_list==1){$('input[name="pref[]"]').attr("checked",false);}
$('#facilities_result_area').slideUp('slow',function(){$('#slide').slideUp('fast');});});mycenter=0;}catch(error){}},clearAll:function(is_clear_pref_list){try{$('.btn_clear02').css('cursor','default');$('.map a').removeClass('on');$('.pref_list').slideUp('normal',function(){$('#facilities_result_area ul').empty();$('span.center_pref_list input[name="pref[]"]').attr("checked",false);if(typeof is_clear_pref_list!="undefined"&&is_clear_pref_list==1){$('input[name="pref[]"]').attr("checked",false);}
$('#facilities_result_area').slideUp('slow',function(){$('#slide').slideUp('fast',function(){$('.center_pref_list').slideUp('slow');if(is_clear_pref_list==0){$('.pref_list').slideUp('slow');};$('.all_pref_list').slideUp('slow');});});});mycenter=0;}catch(error){}},htmlEntityDecode:function(str){var _tempElementId='temp_json_area';var _returnString=null;if($("body")){var oObj=$("<textarea id=\""+_tempElementId+"\" style=\"width:0;height:0;display:none;\"></textarea>");oObj.html(str);_returnString=oObj.val();oObj.remove();oObj=null;_returnString=_returnString.split("&#039;").join("'");_returnString=_returnString.split("&#39;").join("'");}else{_returnString=false;}
return _returnString;},updatePrintTargetList:function(){try{var has_error_id=arguments[0];var postData=new Object();if(typeof has_error_id!="undefined"&&has_error_id>0){postData.has_error_id=has_error_id;}
$.ajax({url:"/card/facilities/cookie_print_data.html",dataType:"json",type:'post',data:postData,async:false,success:function(data){try{var input_str="";for(var i=0;i<data.length;i++){var currentData=data[i];if(typeof currentData.has_error_id!="undefined"){$('.sidebar p.alert_mes').css('display','block');if($('input:checkbox[name="sc_sightseeingid[]"][value="'+currentData.has_error_id+'"]').attr("checked")==true){$('input:checkbox[name="sc_sightseeingid[]"][value="'+currentData.has_error_id+'"]').attr("checked",false);}}else{$('.sidebar p.alert_mes').css('display','none');input_str+='<li class="select_'+currentData.sc_sightseeingid+'"><input type="checkbox" name="select_facility[]" value="'+
currentData.sc_sightseeingid+'" checked="checked" readonly />&nbsp;&nbsp;'+
currentData.title+"</li>";if($('input:checkbox[name="sc_sightseeingid[]"][value="'+currentData.sc_sightseeingid+'"]').attr("checked")==false){$('input:checkbox[name="sc_sightseeingid[]"][value="'+currentData.sc_sightseeingid+'"]').attr("checked",true);}}}
$("#selector").html(input_str);if(data.length>0){$("#sidebar").css("display","block");$("#selector").css("display","");}else{$("#sidebar").css("display","none");$("#selector").empty();$("#selector").html("");$("#selector").css("display","");};$("#sidebar ul#selector li").each(function(){$(this).on("click",function(event){try{var fac_id=$(this).attr("class");fac_id=fac_id.replace(/select\_/,'');if($('input:checkbox[name="sc_sightseeingid[]"][value="'+fac_id+'"]').prop("checked")){$('input:checkbox[name="sc_sightseeingid[]"][value="'+fac_id+'"]').trigger("click");}else{facilities_search.getCategoryId(fac_id);}}catch(error){}});});}catch(error){}}});}catch(error){}},getCategoryId:function(){try{var param=new Object();param.id=arguments[0];var checked=$('input[name="sc_sightseeingid[]"][value="'+param.id+'"]');if(checked.prop('checked')){param.mode='add';}else{param.mode='del';}
$.ajax({url:"/card/facilities/cookie_print_data.html",dataType:"json",type:'post',data:param,async:false,success:function(data){try{if(data.length>0&&data[data.length-1].has_error_id){facilities_search.updatePrintTargetList(data[data.length-1].has_error_id);}else{facilities_search.updatePrintTargetList();}}catch(error){}},error:function(){}});}catch(error){}},getPositionForAddress:function(id){try{var sad=$("#s_address_"+id).val();var geocoder=new google.maps.Geocoder();geocoder.geocode({'address':sad},function(results,status){if(status==google.maps.GeocoderStatus.OK){position=results[0].geometry.location;mapDetail.setCenter(results[0].geometry.location);Marker=new google.maps.Marker({position:position,map:mapDetail});Marker.setPosition(results[0].geometry.location);return position;}else{position=new google.maps.LatLng(0,0);alert('住所から場所を特定できませんでした。');return position;}});}catch(e){}},viewMap:function(id){try{var pos_x=$("#pos_x_"+id).val();var pos_y=$("#pos_y_"+id).val();$("#map_canvas_mini").css("display","");var position;if(pos_x==""&&pos_y==""){position=facilities_search.getPositionForAddress(id);var myOptions={zoom:13,center:position,mapTypeId:google.maps.MapTypeId.ROADMAP};}else{position=new google.maps.LatLng(pos_x,pos_y);var myOptions={zoom:13,center:position,mapTypeId:google.maps.MapTypeId.ROADMAP};}
mapDetail=new google.maps.Map(document.getElementById("map_canvas_mini"),myOptions);var Marker=new google.maps.Marker({position:position,map:mapDetail});}catch(e){}},getSearchCondition:function(){var data=new Object();try{data=$('form[name=facilities_search_form]').serialize();}catch(e){data=null;}
return data;},search:function(){try{var data=facilities_search.getSearchCondition();var checked_pref=$('input[name="pref[]"]:checked');if(checked_pref.length<1&&mycenter==0){alert("都道府県を選択してください。");return;}else{$('#facilities_result_area').show();}
$.ajax({url:"/card/facilities/member_facilities.html",dataType:"html",type:'POST',data:data,async:false,success:function(html){try{var result_area=$('#facilities_result_area').get(0);$('#facilities_result_area').empty();$('#facilities_result_area').html(html);$('.nav_cate_h4_facility').slideDown('normal');if(facilities_search.isHasData){facilities_search.updatePrintTargetList();$('#slide').css('display','block');COMMON.onPageScrollTo('#search_area',1200,0,0);}else{$('#slide').css('display','none');alert("ご選択いただいた県には、現在優待施設はございません。");}}catch(e){}},error:function(){}});}catch(e){};}};