
(function($,window,undefined){var tm=TweenMax;shopSearchApp=function(){this.isInit=false;this._init();};shopSearchApp.prototype={win:$(window),_init:function(){if(this.isInit)return false;this.isInit=true;this._head=$('.result__heading');this._body=$('.result__body');this.w=$(window).width();this.h=$(window).height();this.o=[];this.hit=$('.result__body').length;this.win.on('load',$.proxy(this.onLoad,this));this.win.on('resize onorientationchange',$.proxy(this.onResize,this));},onLoad:function(e){var scope=this;this.onLoadCheck();this.onGetParamBrandsTop();new categorySearch();if($('.result__body--half').size()>0){$('.get-data-height').each(function(){do{$(this).children('.result__body--half:lt(2)').wrapAll('<div class="grid"></div>');}while($(this).children('.result__body--half').length);});$('.grid').each(function(i){var child$=$(this).children('.result__body--half').length;var target_item=$(this).children('.result__body--half').find('.result__body__shop-area');var target_item_length=$(target_item).length;for(var i=0;i<Math.ceil(target_item_length/child$);i++){var maxHeight=0;for(var j=0;j<child$;j++){if($(target_item).eq(i*child$+j).height()>maxHeight){maxHeight=$(target_item).eq(i*child$+j).height();}}
for(var k=0;k<child$;k++){$(target_item).eq(i*child$+k).height(maxHeight);}}});}
if($('body').hasClass('lang_ja')){if($.cookie('log')){var _catID=[];if($.cookie('logTab')){var _logTab=$.cookie('logTab');if(_logTab=='tab1-content'){$('#tab2-content').removeClass('active');$('#nav-tab2').removeClass('active');}
if(_logTab=='tab2-content'){$('#tab1-content').removeClass('active');$('#nav-tab1').removeClass('active');}
if(_logTab=='tab3-content'){$('#tab3-content').removeClass('active');$('#nav-tab3').removeClass('active');}
$('#'+_logTab).addClass('active');$('#nav-'+_logTab).addClass('active');}
if($.cookie('logCatID')){var json=$.cookie('logCatID');var _logCatID=JSON.parse(json);}
if($.cookie('logCatClass')){var json=$.cookie('logCatClass');var _logCatClass=JSON.parse(json);}
if($.cookie('logRefine')){var json=$.cookie('logRefine');var _logRef=JSON.parse(json);}else{var _logRef='';}
if($.cookie('logRefineID')){var json=$.cookie('logRefineID');var _logRefID=JSON.parse(json);}
var _active=_logCatClass.length;var _activeRef=_logRefID.length;if(_active>0){$('#'+_logTab+' .result__body').css({display:'none'});$('#'+_logTab+' .result__heading').css({display:'none'});$('.category-all').prop('checked',false);$('.category-all').parents('li').removeClass('active');}else{if(_activeRef>0){$('#'+_logTab+' .result__body').css({display:'none'});$('#'+_logTab+' .result__heading').css({display:'none'});$('#'+_logTab+' '+_logRef).show();}}
for(i=0;i<_active;i++){$(_logCatID[i]).addClass('active');$(_logCatID[i]).find('input').prop('checked',true);$('#'+_logTab+' '+_logCatClass[i]+_logRef).show();}
if(_activeRef>0){$('#'+_logTab+' '+_logRefID).addClass('active');$('#'+_logTab+' '+_logRefID).find('input').prop('checked',true);}
$('.nav-tabs li,.side__nav-category dt, side__nav-category dd').click(function(){$.removeCookie('log');$.removeCookie('logTab');$.removeCookie('logCatID');$.removeCookie('logCatClass');$.removeCookie('logRefine');$.removeCookie('logRefineID');});}}
$('.result').each(function(){var b=$(this).find('.result__body:visible'),h=$(this).find('.result__heading'),bl=$(b).length;if(bl===0){$(h).hide();}else{$(h).show();}});this.onResize();if($('#nav-tab2').hasClass('active')){$('.sprite-brands-btn_all').on('click',()=>{const $btnCat=$('#tab2-content .search-categories .js-check');$btnCat.removeClass('active');$btnCat.find('input').prop('checked',false);$('#tab2-content .sprite-brands-btn_all').addClass('active');$('#tab2-content .sprite-brands-btn_all').find('input').prop('checked',true);shopSearch.onSearchFilter('tab2-content','<input class="js-lazy-update" type="checkbox" name="cat[]" value="'+0+'" id="search-category'+0+'">');})}},onResize:function(){this.w=$(window).width();this.h=$(window).height();$(this.rw).push(this.w);$(this.rh).push(this.h);this.o.push(new onChips(this.w,this.h));},onLog:function(_logTab,_logCatID,_logCatClass,_logRefClass,_logRefineID){$('.js-log a').click(function(){var jsonCatID=JSON.stringify(_logCatID);var jsonCatClass=JSON.stringify(_logCatClass);var jsonlogRefClass=JSON.stringify(_logRefClass);var jsonlogRefID=JSON.stringify(_logRefineID);$.cookie('log','flag');$.cookie('logTab',_logTab);$.cookie('logCatID',jsonCatID);$.cookie('logCatClass',jsonCatClass);$.cookie('logRefine',jsonlogRefClass);$.cookie('logRefineID',jsonlogRefID);});},onGetParamBrandsTop:function(){var scope=this;$.extend({getParameter:function getParameter(){var arg=new Object;var pair=location.search.substring(1).split('&');for(i=0;pair[i];i++){var kv=pair[i].split('=');arg[kv[0]]=kv[1];}
return arg;}});var args=$.getParameter();if(args.mode=="c"){if(args.v){var center=parseInt(args.v)+1;$('.brands-framelist__name').each(function(){$(this).children('td:nth-child('+center+')').addClass('select-center');});}}
if($('#nav-tab2').hasClass('active')){const catId=args['cat[]'];const $btnCat=$('#tab2-content .search-categories__items .js-check');if(catId){$btnCat.removeClass('active');$btnCat.find('input').prop('checked',false);for(var i=0;i<$btnCat.length;i++){const $btn=$btnCat.eq(i);if($btn.attr('id')==='search-category'+catId){$btn.addClass('active');$btn.find('input').prop('checked',true);shopSearch.onSearchFilter('tab2-content','<input class="js-lazy-update" type="checkbox" name="cat[]" value="'+catId+'" id="search-category'+catId+'">');}}}}},onLoadCheck:function(){var scope=this;$('#tab1-content .search-categories__items li').each(function(){if($(this).find('input').prop('checked')==true){$(this).addClass('active');var isthis=$(this);scope.onSearchFilter('tab1-content',isthis);}else{$(this).removeClass('active');}});$('#tab1-content .search-refine__items input').each(function(){if($(this).prop('checked')==true){$(this).parents('li').addClass('active');var isthis=$(this);scope.onSearchFilter('tab1-content',isthis);}else{$(this).parents('li').removeClass('active');}});$('#tab2-content .search-categories__items li').each(function(){if($(this).find('input').prop('checked')==true){$(this).addClass('active');var isthis=$(this);scope.onSearchFilter('tab2-content',isthis);}else{$(this).removeClass('active');}});$('#tab2-content .search-refine__items input').each(function(){if($(this).prop('checked')==true){$(this).parents('li').addClass('active');var isthis=$(this);scope.onSearchFilter('tab2-content',isthis);}else{$(this).parents('li').removeClass('active');}});},onSearchFilter:function(_tab,_index){$('#'+_tab+' .result__body').css({display:'none'});$('#'+_tab+' .result__heading').css({display:'none'});if($(_index).prop('checked')){$(_index).prop('checked',true);$(_index).parents('li').addClass('active');}else{$(_index).prop('checked',false);$(_index).parents('li').removeClass('active');}
if($(_index).attr('class')!='category-all'){$('#'+_tab+' .category-all').prop('checked',false);$('#'+_tab+' .category-all').parents('li').removeClass('active');}else{$('#'+_tab+' .search-categories__items li').not('.sprite-brands-btn_all').removeClass('active');$('#'+_tab+' .search-categories__items li').not('.sprite-brands-btn_all').find('input').prop('checked',false);$('#'+_tab+' .category-all').prop('checked',true);$('#'+_tab+' .category-all').parents('li').addClass('active');}
var _catId=$(_index).parents('li').attr('id');var _catProp=$(_catId).find('input');var _catClass='.'+_catId;var _catActiveLength=$('#'+_tab+' .search-categories__items .active').length;var _refActiveLength=$('#'+_tab+' .search-refine__items .active').length;if(_catActiveLength==0){$('#'+_tab+' .category-all').prop('checked',true);$('#'+_tab+' .category-all').parents('li').addClass('active');}
var _classCategory=[];var _idCategory=[];$.each($('#'+_tab+' .search-categories__items .js-check.active'),function(){var _id=$(this).attr('id');_classCategory.push('.'+_id);_idCategory.push('#'+_id);});var _classRefine=[];var _classRefine2=[];var _IDRefine=[];$.each($('#'+_tab+' .search-refine__items .js-check.active'),function(){var _id=$(this).attr('id');_classRefine.push(_id);_classRefine2.push('.'+_id);_IDRefine.push('#'+_id);});if(_refActiveLength>0){var _classRefineJoin='.'+_classRefine.join('.');}else{var _classRefineJoin=_classRefine.join('.');}
if(_tab!='tab3-content'){if($('#'+_tab+' .category-all').prop('checked')){if(_refActiveLength>0){$('#'+_tab+' '+_classRefineJoin).show();}else{$('.result__heading').show();$('.result__body').show();}}else{for(i=0;i<_catActiveLength;i++){$('#'+_tab+' '+_classCategory[i]+_classRefineJoin).show();}}}else{if($(_index).prop('checked')){$('#'+_tab+' .result__heading'+_classRefineJoin).show();$('#'+_tab+' .result__body'+_classRefineJoin).show();}else{$('#'+_tab+' .result__heading').show();$('#'+_tab+' .result__body').show();}}
if(_refActiveLength>0){$('#'+_tab+' .result').each(function(){var _visibleBlock=$(this).children('.result__body:visible').length;if(_visibleBlock==0){$(this).find('.result__heading').hide();}});}
function sum(_hiddenItems){var result=0;for(var i=0,l=_hiddenItems.length;i<l;i++){result+=_hiddenItems[i];}
return result;}
var _hiddenItem=[];$('.result').each(function(i){var _visibleBlock=_hiddenItem.push($(this).find('.result__body:visible').length);});var _hiddenTotal=sum(_hiddenItem);if(_hiddenTotal==0){$('.result__message').show();$('.text-favorite').hide();$('.switchLayout--center,.switchLayout').css({display:'none'});$('.switchLayout--center,.switchLayout').css({display:'none'});}else{$('.result__message').hide();$('.text-favorite').show();$('.switchLayout--center,.switchLayout').css({display:'block'});}
this.onLog(_tab,_idCategory,_classCategory,_classRefineJoin,_IDRefine);var e=$('.shopCi').find('.ciGrid__item:visible'),l=$(e).length;this.hit=$('.result__body:visible').length;$('#js-hit-number').html(this.hit);}};categorySearch=function(){this.onCategoryStart();}
categorySearch.prototype={onCategoryStart:function(){this.onCategoryCheck();this.onRefineCheck();},onCategoryCheck:function(){$('#tab1-content .search-categories__items input').click(function(){var _btn=this;var _tab='tab1-content';shopSearch.onSearchFilter(_tab,_btn);});$('#tab2-content .search-categories__items input').click(function(){var _btn=this;var _tab='tab2-content';shopSearch.onSearchFilter(_tab,_btn);});},onRefineCheck:function(){$('#tab1-content .search-refine__items input').click(function(){var _btn=this;var _tab='tab1-content';shopSearch.onSearchFilter(_tab,_btn);});$('#tab2-content .search-refine__items input').click(function(){var _btn=this;var _tab='tab2-content';shopSearch.onSearchFilter(_tab,_btn);});$('#tab3-content .search-refine__items input').click(function(){var _btn=this;var _tab='tab3-content';shopSearch.onSearchFilter(_tab,_btn);});}};onChips=function(window_width,window_height){this.rw=window_width;this.rh=window_height;this.onMouseAction();}
onChips.prototype={onMouseAction:function(e){var scope=this,b=$('.onChip'),t=$('#legend-ico-shop'),w=this.rw,u=0;$(b).mouseover(function(){var s=Math.floor($(this).offset().top+25),e=s-30,l=$(this).offset().left,p=l+440;if(w-p>0){u=Math.floor(l+40);}else{u=Math.floor(l-440);}
$(t).css({top:s+'px',left:u+'px'});tm.fromTo($(t),0.6,{css:{opacity:0,display:'none'}},{css:{opacity:1,display:'block',top:e+'px'},ease:'Power4.easeInOut'});});$(b).mouseout(function(){tm.to($(t),0.4,{css:{'opacity':'0',display:'none'}});});}}
if(!('console'in window)){window.console={};window.console.log=function(str){return str};}
$(function(){window.shopSearch=new shopSearchApp();});})(jQuery,this);